services:

  nginx:
    container_name: nginx-nextcloud
    image: nginx:latest
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ${NEXTCLOUD_DIR}:/var/www/html
      - ${DATA_DIR}:/data
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - nextcloud
    depends_on:
      - php-fpm-nextcloud
      - redis-nextcloud
      - mariadb-nextcloud
    restart: unless-stopped


  php-fpm-nextcloud:
    container_name: php-fpm-nextcloud
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      tags:
        - localhost/php-fpm-nextcloud:latest
    volumes:
      - ${NEXTCLOUD_DIR}:/var/www/html
      - ${DATA_DIR}:/data
      # custom PHP configs (sem sobrescrever as extens√µes)
      - ./php-fpm/conf.d/90-nextcloud.ini:/usr/local/etc/php/conf.d/90-nextcloud.ini:ro
      - ./php-fpm/conf.d/90-apcu.ini:/usr/local/etc/php/conf.d/90-apcu.ini:ro
      - ./php-fpm/conf.d/99-opcache.ini:/usr/local/etc/php/conf.d/99-opcache.ini:ro
      # FPM pool
      - ./php-fpm/conf-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - nextcloud
    restart: unless-stopped


  mariadb-nextcloud:
    container_name: mariadb-nextcloud
    image: mariadb:10.11
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${MARIADB_DIR}:/var/lib/mysql
      - ./mariadb/conf:/etc/mysql/conf.d

    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASS}
      - MYSQL_PASSWORD=${MARIADB_PASS}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - nextcloud
    restart: unless-stopped


  redis-nextcloud:
    container_name: redis-nextcloud
    image: redis:latest
    restart: unless-stopped
    networks:
      - nextcloud


  cron-nextcloud:
    container_name: cron-nextcloud
    image: localhost/php-fpm-nextcloud:latest
    command: ["bash", "-c", "while true; do echo \"Running cron job\"; php /var/www/html/cron.php; sleep 300; done"]
    user: www-data
    networks:
      - nextcloud
    volumes:
      - ${NEXTCLOUD_DIR}:/var/www/html
      - ${DATA_DIR}:/data
    depends_on:
      - php-fpm-nextcloud
      - redis-nextcloud
      - mariadb-nextcloud
    restart: unless-stopped


networks:
  nextcloud:
    driver: bridge
